source 'https://rubygems.org'
source 'https://rails-assets.org'
ruby '2.1.2'

gem 'rails', '4.0.4'
gem 'mysql2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'sass-rails', '>= 3.2'
gem 'autoprefixer-rails'
gem 'haml-rails'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-pocket'
gem 'simple_form', '>= 3.1.0.rc2'
gem 'thin'
gem 'twitter'
gem 'koala'
gem 'randumb'
gem 'nokogiri', '1.6.1'
gem 'sinatra', '>= 1.3.0', require: nil
gem 'rb-gsl'
gem 'madeleine'
gem 'classifier'
gem 'treat'
gem 'omnicat-bayes'
gem 'typhoeus'
gem 'pismo', github: 'andyatkinson/pismo', branch: 'open_uri_redirections'
gem 'parallel'
gem 'metainspector'
gem 'htmlentities'
gem 'wikipedia'
gem 'rocket_tag', git: 'git://github.com/legendetm/rocket_tag.git'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'immigrant'
gem 'guard-redis'
gem 'guard-sidekiq'

gem 'therubyracer', platforms: :ruby
gem 'less-rails-bootstrap'
gem 'jquery-ui-rails'
gem 'bourbon'

gem 'rails-assets-select2'
gem 'rails-assets-lodash'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'foreman'
  gem 'html2haml'
  gem 'hub', require: nil
  gem 'quiet_assets'
  gem 'rails_layout'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'dotenv-rails'
  gem 'awesome_print'
  gem 'colored'
  gem 'bond'
  gem 'pry'
  gem 'pry-rails'
  gem 'pry-byebug'
  gem 'pry-coolline'
  gem 'pry-remote'
  gem 'pry-macro'
  gem 'pry-theme'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
end

gem 'ffi', '<1.9.3'

# treat
gem 'graphr'
gem 'linguistics'
gem 'engtagger'
gem 'open-nlp'
gem 'stanford-core-nlp'
gem 'rwordnet'
gem 'scalpel'
gem 'fastimage'
gem 'decisiontree'
gem 'whatlanguage'
gem 'zip'
gem 'nickel'
gem 'tactful_tokenizer'
gem 'srx-english'
gem 'punkt-segmenter'
gem 'chronic'
gem 'uea-stemmer'
gem 'rbtagger'
gem 'ruby-stemmer'
gem 'activesupport'
gem 'rb-libsvm'
gem 'liblinear-ruby-swig'
gem 'ruby-fann'
gem 'fuzzy-string-match'
gem 'levenshtein-ffi'
gem 'tf-idf-similarity'
gem 'kronic'

gem 'sidekiq'