source 'https://rubygems.org'
ruby '2.1.1'

gem 'rails', '4.0.4'
gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 1.2'
gem 'bootstrap-sass'
gem 'haml-rails'
gem 'mysql2'
gem 'omniauth'
gem 'omniauth-facebook'
gem 'omniauth-twitter'
gem 'omniauth-pocket'
gem 'simple_form'
gem 'thin'
gem 'twitter'
gem 'koala'
gem 'sidekiq'
gem 'sinatra', '>= 1.3.0', require: nil
gem 'treat'
gem 'omnicat-bayes'
gem 'pismo'
gem 'metainspector'
gem 'wikipedia'
gem 'net-http-persistent'
gem 'acts-as-taggable-on'
gem 'will_paginate'
gem 'will_paginate-bootstrap'
gem 'immigrant'

gem 'therubyracer', platforms: :ruby
gem 'less-rails-bootstrap'
gem 'jquery-ui-rails'
gem 'designmodo-flatuipro-rails', '~> 1.2.5.0.branch'
gem 'bourbon'

group :development do
  gem 'better_errors'
  gem 'foreman'
  gem 'html2haml'
  gem 'hub', require: nil
  gem 'quiet_assets'
  gem 'rails_layout'
end

group :development, :test do
  gem 'factory_girl_rails'
  gem 'rspec-rails'
  gem 'dotenv-rails'
  gem 'awesome_print'
  gem 'colored'
  gem 'pry'
  gem 'pry-coolline'
  gem 'pry-rails'
  gem 'pry-remote'
  gem 'pry-nav'
  gem 'binding_of_caller'
end

group :test do
  gem 'capybara'
  gem 'database_cleaner', '1.0.1'
  gem 'email_spec'
end

# treat
gem 'graphr'
gem 'linguistics'
gem 'engtagger'
gem 'open-nlp'
gem 'stanford-core-nlp'
gem 'rwordnet'
gem 'scalpel'
gem 'fastimage'
gem 'decisiontree'
gem 'whatlanguage'
gem 'zip'
gem 'nickel'
gem 'tactful_tokenizer'
gem 'srx-english'
gem 'punkt-segmenter'
gem 'chronic'
gem 'uea-stemmer'
gem 'rbtagger'
gem 'ruby-stemmer'
gem 'activesupport'
gem 'rb-libsvm'
gem 'liblinear-ruby-swig'
gem 'ruby-fann'
gem 'fuzzy-string-match'
gem 'levenshtein-ffi'
gem 'tf-idf-similarity'
gem 'kronic'
